### ISSUE TITLE
Q: How to add vertical panels for arc-theme?

### ISSUE THREAD

**Issue by mzwlevi** [andyburris/logseq-arc-theme#13]
The arc theme is awesome, I love it!

Is there anyway to add the vertical panels? Thank you, This will be useful when open multi-panels.

![Screen Shot 2022-10-19 at 18 01 24](https://user-images.githubusercontent.com/78029539/196661121-ac952881-8f51-4fd0-a1f9-b40e3ca8eb4e.png)

**Comment by mzwlevi** [comment]
Arc theme is the best which I have seen in Logseq theme market

**Comment by andyburris** [comment]
Hi! Can you elaborate a little bit more on what you mean by vertical panels? From my understanding of Logseq there's only one right side panel that can show at a time (aka the one that's showing in your screenshot)

**Comment by mzwlevi** [comment]
> Hi! Can you elaborate a little bit more on what you mean by vertical panels? From my understanding of Logseq there's only one right side panel that can show at a time (aka the one that's showing in your screenshot)

Examples:
https://github.com/r-hegde/logseq-vertical-panels
![Screen Shot 2022-10-21 at 08 27 13](https://user-images.githubusercontent.com/78029539/197083924-8d298394-2397-4595-b791-657c97a7e32e.png)

https://github.com/JimmyLv/digital-garden
![Screen Shot 2022-10-21 at 08 29 25](https://user-images.githubusercontent.com/78029539/197084101-ea39fe06-4c76-4218-94fe-6d8033380577.png)

**Comment by andyburris** [comment]
Hi, sorry for the delay on getting to this. I've been thinking about my general strategy for plugins, and have decided not to support them per #20 but instead let users submit snippets to fix plugins in GitHub Discussions. 

I don't know if you ended up finding a fix (if not try using the inspect tool with `Command` `Shift` `I` to figure out a the CSS needed to fix it, then add it to `custom.css`), but if you did would you be willing to add it as a discussion post? 

Either way, I'm going to close this issue for now. Thank you!
