### ISSUE TITLE
Modals not wide enough to fit content

### ISSUE THREAD

**Issue by aadilayub** [andyburris/logseq-arc-theme#17]
Thanks for writing this theme! 

I noticed the settings and plugin selection popups are narrower than the containing content:

![image](https://user-images.githubusercontent.com/31581044/205958373-75d37f69-540a-4477-b363-8b6ad9cec74d.png)

![image](https://user-images.githubusercontent.com/31581044/205958518-d911ecdb-6fef-47d9-b14f-1d8bbe4eb061.png)

**Comment by aadilayub** [comment]
I fiddled around in the inspector and found the modals go back to normal width when you disable [this](https://github.com/andyburris/logseq-arc-theme/blob/main/custom.scss#L561) CSS rule:

![image](https://user-images.githubusercontent.com/31581044/205960223-a37a07f6-22da-48bb-b091-af29c1cd1528.png)

**Comment by andyburris** [comment]
Thank you! I've noticed this too, and am debating two solutions:

1. Make the just the plugins marketplace popup wider (and maybe the settings popup slightly wider too)
    - Pros: easy to implement, more in line with standard Logseq UI
    - Cons: would make popup sizes inconsistent
2. Force the content inside the plugins marketplace to wrap to current popup width (maybe make all popups slightly wider)
    - Pros: standardizes popups in UI
    - Cons: takes more work, might make marketplace slightly cramped if it's not possible to decrease number of grid columns

I'm still deciding which I'm going to go with (will probably prototype solutions for both and compare), but if you have any thoughts, let me know

**Comment by aadilayub** [comment]
Personally I would go for making the pops wider. Option 2 feels like it would be prone to breakage, and IMO it is really important to have the settings and plugin modals functional, otherwise it is hard to use the theme on a regular basis.

**Comment by andyburris** [comment]
Should be fixed in the latest update-- sorry for the delay!
